/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#002c37',
        'on-primary-fixed-variant': '#004c5d',
        'surface-container-low': '#0b1031',
        'on-primary-container': '#004352',
        'outline-variant': '#414665',
        'secondary': '#b3a2f7',
        'on-tertiary-fixed': '#1f0052',
        'surface-tint': '#6dddff',
        'error': '#ff716c',
        'surface-container-lowest': '#000000',
        'surface-dim': '#070b28',
        'tertiary': '#ac89ff',
        'surface-container': '#10163a',
        'tertiary-dim': '#874cff',
        'on-tertiary-container': '#f8f1ff',
        'tertiary-container': '#7000ff',
        'surface-variant': '#1b224c',
        'on-secondary': '#31206d',
        'error-dim': '#d7383b',
        'primary-fixed-dim': '#00c3eb',
        'primary-dim': '#00c3eb',
        'secondary-fixed': '#d6cbff',
        'on-primary': '#004c5e',
        'inverse-on-surface': '#4e5373',
        'on-secondary-container': '#d5c9ff',
        'primary-container': '#00d2fd',
        'background': '#070b28',
        'on-tertiary-fixed-variant': '#4700a7',
        'on-tertiary': '#290067',
        'primary': '#6dddff',
        'on-secondary-fixed': '#372673',
        'surface-container-high': '#161c43',
        'tertiary-fixed': '#bda1ff',
        'inverse-primary': '#00687e',
        'secondary-fixed-dim': '#c8bbff',
        'on-surface': '#e2e3ff',
        'on-error-container': '#ffa8a3',
        'on-secondary-fixed-variant': '#544492',
        'secondary-dim': '#a595e9',
        'tertiary-fixed-dim': '#b190ff',
        'surface-container-highest': '#1b224c',
        'surface': '#070b28',
        'primary-fixed': '#00d2fd',
        'on-background': '#e2e3ff',
        'inverse-surface': '#fbf8ff',
        'surface-bright': '#212855',
        'outline': '#6f7395',
        'on-surface-variant': '#a5a9ce',
        'on-error': '#490006',
        'error-container': '#9f0519',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

